use std::path::Path;

use serde_json::Value;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) enum ScaffoldMode {
    CanonicalTypeScriptTailwind,
    ExistingTypeScriptPlainCss,
    ExistingJavaScriptTailwind,
    ExistingPlainJavaScript,
}

pub(super) fn detect(root: &Path) -> ScaffoldMode {
    let Some(package) = read_package(root) else {
        return ScaffoldMode::CanonicalTypeScriptTailwind;
    };
    match (
        uses_typescript_toolchain(root, &package),
        uses_tailwind_toolchain(root, &package),
    ) {
        (true, true) => ScaffoldMode::CanonicalTypeScriptTailwind,
        (true, false) => ScaffoldMode::ExistingTypeScriptPlainCss,
        (false, true) => ScaffoldMode::ExistingJavaScriptTailwind,
        (false, false) => ScaffoldMode::ExistingPlainJavaScript,
    }
}

impl ScaffoldMode {
    pub(super) fn uses_typescript(self) -> bool {
        matches!(
            self,
            Self::CanonicalTypeScriptTailwind | Self::ExistingTypeScriptPlainCss
        )
    }

    pub(super) fn uses_tailwind(self) -> bool {
        matches!(
            self,
            Self::CanonicalTypeScriptTailwind | Self::ExistingJavaScriptTailwind
        )
    }
}

pub(super) fn uses_typescript_toolchain(root: &Path, package: &Value) -> bool {
    [
        "typescript",
        "@types/node",
        "@types/react",
        "@types/react-dom",
    ]
    .iter()
    .any(|name| package_has_dependency(package, name))
        || root.join("tsconfig.json").is_file()
        || source_tree_contains_extension(root, &["ts", "tsx"])
}

fn uses_tailwind_toolchain(root: &Path, package: &Value) -> bool {
    package_has_dependency(package, "tailwindcss")
        || [
            "tailwind.config.ts",
            "tailwind.config.js",
            "tailwind.config.cjs",
            "tailwind.config.mjs",
            "postcss.config.js",
            "postcss.config.cjs",
            "postcss.config.mjs",
        ]
        .iter()
        .any(|rel| root.join(rel).is_file())
        || source_tree_contains(root, "@tailwind")
}

fn read_package(root: &Path) -> Option<Value> {
    let content = std::fs::read_to_string(root.join("package.json")).ok()?;
    serde_json::from_str(&content).ok()
}

fn package_has_dependency(package: &Value, name: &str) -> bool {
    ["dependencies", "devDependencies"]
        .iter()
        .filter_map(|section| package.get(section).and_then(Value::as_object))
        .any(|dependencies| dependencies.contains_key(name))
}

fn source_tree_contains_extension(root: &Path, extensions: &[&str]) -> bool {
    source_files(root).any(|path| {
        path.extension()
            .and_then(|extension| extension.to_str())
            .is_some_and(|extension| extensions.contains(&extension))
    })
}

fn source_tree_contains(root: &Path, needle: &str) -> bool {
    source_files(root)
        .any(|path| std::fs::read_to_string(path).is_ok_and(|content| content.contains(needle)))
}

fn source_files(root: &Path) -> impl Iterator<Item = std::path::PathBuf> {
    ["src/app", "app", "src/pages", "pages"]
        .into_iter()
        .flat_map(|rel| collect_files(&root.join(rel)))
}

fn collect_files(root: &Path) -> Vec<std::path::PathBuf> {
    let Ok(entries) = std::fs::read_dir(root) else {
        return Vec::new();
    };
    entries
        .flatten()
        .flat_map(|entry| {
            let path = entry.path();
            if path.is_dir() {
                collect_files(&path)
            } else {
                vec![path]
            }
        })
        .collect()
}

pub(super) fn plain_layout() -> &'static str {
    r#"import "./globals.css";

export const metadata = {
  title: "Interactive Challenge",
  description: "A compact interactive challenge generated by commandagent",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
"#
}

pub(super) fn plain_page() -> &'static str {
    r#""use client";

import { useState } from "react";

export default function Page() {
  const [count, setCount] = useState(0);
  return (
    <main data-anvil-state={JSON.stringify({ count })}>
      <h1>INTERACTIVE CHALLENGE</h1>
      <p>Count: {count}</p>
      <button data-anvil-action="primary" onClick={() => setCount((value) => value + 1)}>
        Start
      </button>
      <button data-anvil-action="restart" onClick={() => setCount(0)}>
        Reset
      </button>
    </main>
  );
}
"#
}

pub(super) fn plain_css() -> &'static str {
    "* { box-sizing: border-box; }\nhtml, body { margin: 0; min-height: 100%; }\nbody { background: #05070d; color: #eef7ff; font-family: sans-serif; }\nmain { min-height: 100vh; padding: 2rem; }\nbutton { margin-right: 0.75rem; font: inherit; }\n"
}
