//! The one place the fixed identifiers live (Issue #548).
//!
//! A *fixed identifier* is a value the product itself owns: every `event` name,
//! every `commandagent.*` schema name, the status/verdict/result machine values,
//! and the built-in tool/protocol names. They must never be rewritten by the
//! secret scrub, and a credential value that equals one of them (or is a
//! substring of one) is refused at registration because redacting it would
//! corrupt the schema.
//!
//! There is no second copy: [`fixed_schema_keys`] and [`is_fixed_identifier`]
//! read these same constants, and the completeness test in `tests.rs` scans the
//! source literals and fails when a new event or schema name is missing here.

/// Keys whose value is a fixed identifier inside a schema container. Such a
/// value is preserved only when it is itself a fixed identifier
/// ([`is_fixed_identifier`]); any other value is scrubbed.
pub const FIXED_SCHEMA_KEYS: &[&str] = &[
    "event",
    "schema_version",
    "status",
    "verdict",
    "type",
    "kind",
    "classification",
    "level",
    "ok",
    "phase",
    "stage",
    "family",
    "envelope_version",
    "lifecycle_stage",
    "tool_name",
    "step_kind",
    "judgement",
    "direction",
    "action",
];

/// Keys whose direct children are themselves a fixed schema (their schema keys
/// are fixed at depth two). `evidence_envelope` is the real product case.
pub const FIXED_SCHEMA_CONTAINERS: &[&str] = &["evidence_envelope"];

/// Every fixed identifier: all event names, every `commandagent.*` schema name,
/// the status/verdict/result machine values, and the built-in tool/protocol
/// names.
pub const FIXED_IDENTIFIERS: &[&str] = &[
    "Bash",
    "Edit",
    "Glob",
    "Grep",
    "Read",
    "Write",
    "aborted",
    "anchor_stagnation_interlock",
    "artifact_stagnation_feedback",
    "bash_path_confinement_rejected",
    "blocked",
    "blocked_by_dependency_setup",
    "browser_interaction_probe",
    "browser_probe",
    "build_pass",
    "command_timeout_repetition",
    "commandagent.eval.score/v0",
    "commandagent.extensions/v1",
    "commandagent.fetch-cache/v0",
    "commandagent.fetch-evidence/v0",
    "commandagent.fetch-recording/v0",
    "commandagent.fetch/v0",
    "commandagent.gui-contract/v1",
    "commandagent.gui-working-directory/v1",
    "commandagent.headless-summary/v1",
    "commandagent.pack.assist/v0",
    "commandagent.pack.eval/v0",
    "commandagent.pass/v1",
    "commandagent.run-trace/v1",
    "commandagent.runs/v1",
    "commandagent.score-checkpoint/v0",
    "community_profile_verification",
    "compile_error_extraction",
    "compile_no_snapshot_narrow_retry",
    "compile_rollback_applied",
    "compile_rollback_context_carried",
    "compile_rollback_failed",
    "compile_rollback_skipped",
    "compile_snapshot_saved",
    "complete",
    "completed",
    "completion_contract_bound",
    "completion_contract_command_observation",
    "completion_verify",
    "context_truncation_suspected",
    "contract_attribute_repair_guidance",
    "contract_observation_incomplete",
    "declarative_command_check_result",
    "degraded",
    "dependency_build_lifecycle",
    "dependency_denial_guidance",
    "dependency_setup_reconciliation",
    "depth_profile",
    "deterministic_step_plan_used",
    "dev_server_lifecycle",
    "dev_server_port_in_use_retry",
    "draft",
    "edit_anchor_recovery",
    "edit_anchor_salvaged",
    "empty_response_escalation",
    "empty_response_recovered",
    "error",
    "escalation_carryover",
    "expected_fail_python_traceback_observed",
    "extension_tool_call",
    "extension_tool_rejected",
    "extension_tool_result",
    "extracted",
    "fail",
    "failed",
    "fallback",
    "fallback_decision",
    "final_acceptance_cycle_complete",
    "final_acceptance_cycle_summary",
    "final_acceptance_deterministic_remedies",
    "final_acceptance_repair_complete",
    "final_acceptance_repair_exhausted",
    "final_acceptance_repair_failed",
    "final_acceptance_repair_no_source_change",
    "final_acceptance_repair_start",
    "fix_evidence_recorded",
    "fix_plan_synthesized",
    "fix_regression_contract_bound",
    "fix_reproducer_suggested",
    "fixture",
    "foreign_toolchain_detected",
    "full",
    "function",
    "future_phase_annotation",
    "generic_contract_bound",
    "gui_trial_stop_completed",
    "gui_trial_stop_requested",
    "h05_collision",
    "hidden_path_feedback",
    "hook_snapshot_feedback",
    "hook_snapshot_restored",
    "hook_snapshot_saved",
    "host_env_contamination",
    "host_env_normalized",
    "human_directive_confirmed",
    "human_directive_continuation_started",
    "human_directive_continuation_stopped",
    "human_directive_proposed",
    "incomplete",
    "ingest_candidate_ids_injected",
    "ingest_plan_synthesized",
    "ingest_snapshot_structure_injected",
    "inspect_command_normalized",
    "inspect_mutation_tool_rejected",
    "intent_resolved",
    "interrupted",
    "investigation_adjudicated",
    "investigation_plan_synthesized",
    "legacy_detail",
    "loop_stop",
    "native_tool_parse_retry_feedback",
    "next_action_selected",
    "no_progress_feedback",
    "normal_marker",
    "not_run",
    "observed",
    "ok",
    "other_path",
    "pack_check_result",
    "pack_injected",
    "panic_caught",
    "partial",
    "pass",
    "passed",
    "path_fallback_evaluated",
    "pending",
    "phase_verification_result",
    "pipeline_error_extraction",
    "plan_final_contract",
    "plan_preset_resolved",
    "plan_step_started",
    "planner_error",
    "planner_fallback_plan",
    "planner_plan_sanitized",
    "planner_quality_issue",
    "planner_quality_retry",
    "planner_quality_retry_degraded",
    "planner_quality_retry_exhausted",
    "planner_quality_warning",
    "planner_raw_output_shape",
    "planner_verify_command_normalized",
    "preclosure_verifier_replacements_validated",
    "preset_step_converted",
    "preset_ultra_plan_used",
    "probe_preflight",
    "profile_behavior_probe",
    "profile_inferred",
    "profile_invariant_repair",
    "profile_invariant_repair_build_verify",
    "profile_reinferred",
    "protected_path_mutation_rejected",
    "provider_error",
    "provider_parse_error",
    "provider_request",
    "provider_response",
    "provider_retry",
    "provider_turn_aborted_by_user",
    "provider_turn_duration",
    "provider_turn_timeout",
    "provider_turn_timeout_recovered",
    "python_cli_implementation_plan_canonicalized",
    "read_only_stagnation_feedback",
    "read_only_tool_rejected",
    "ready",
    "recovery_boundary_snapshot",
    "recovery_candidate_completion_requirements_bound",
    "recovery_candidate_verify_commands_bound",
    "recovery_capability_observer_bound",
    "recovery_completion_contract_bound",
    "recovery_continuation_prepared",
    "recovery_control_retained",
    "recovery_fix_contract_resumed",
    "recovery_fix_safety_verification",
    "recovery_generated_completion_contract_completed",
    "recovery_handoff_fidelity_bound",
    "recovery_handoff_fidelity_failed",
    "recovery_host_final_success_verification_failed",
    "recovery_host_final_success_verification_passed",
    "recovery_observation_effect_policy_bound",
    "recovery_plan_auto_run_complete",
    "recovery_plan_auto_run_start",
    "recovery_preflight_control_audit",
    "recovery_preflight_effect_observation",
    "recovery_preflight_observation",
    "recovery_product_mutation_observed",
    "recovery_promotion_decision",
    "recovery_prompt_save_failed",
    "recovery_prompt_saved",
    "recovery_read_only_post_step_repair_suppressed",
    "recovery_repair_obligation_observed",
    "recovery_step_plan_verify_commands_bound",
    "recovery_treatment_delta",
    "recovery_treatment_promoted",
    "recovery_ultra_plan_save_failed",
    "recovery_verifier_obligations_formed",
    "recovery_verifier_owner_binding",
    "recovery_verifier_plan_admission",
    "recovery_verifier_plan_return_rejected",
    "recovery_verifier_repairability",
    "repair_applied",
    "repair_regeneration",
    "repair_target_reclassified",
    "repair_unreachable",
    "resume_start",
    "route_confirmed",
    "route_proposed",
    "route_unbound_recovery",
    "run_start",
    "run_stop",
    "running",
    "runtime_bash_policy",
    "score_checkpoint",
    "server_reaped",
    "setup_scaffold_completed",
    "side_effect_path_dropped",
    "state_binding_diagnosis",
    "step_capability_evidence_check",
    "step_completion_blocked",
    "step_obligation_scope",
    "step_oracle_tier_degraded",
    "step_prompt_contract",
    "step_short_circuited",
    "step_verify_failure",
    "step_verify_repair",
    "success",
    "test_node_event",
    "time_profile",
    "tool",
    "tool_args_path_malformed",
    "tool_args_path_near_root_corruption",
    "tool_args_path_normalized",
    "tool_args_path_salvaged",
    "tool_args_recovered",
    "tool_call",
    "tool_call_raw",
    "tool_execute",
    "tool_parse_failure",
    "tool_policy_error",
    "tool_read_unchanged",
    "tool_validation_error",
    "tui_command_start",
    "tui_command_stop",
    "ultra_context_initialized",
    "ultra_final_acceptance",
    "ultra_final_acceptance_failed",
    "ultra_partial_artifact_summary",
    "ultra_phase_complete",
    "ultra_phase_context_attached",
    "ultra_phase_context_updated",
    "ultra_phase_failed",
    "ultra_phase_start",
    "ultra_plan_complete",
    "ultra_plan_failed",
    "ultra_plan_generation_attempt",
    "ultra_plan_generation_failed",
    "ultra_plan_generation_metadata_normalized",
    "ultra_plan_generation_retry",
    "ultra_plan_generation_succeeded",
    "ultra_plan_generation_tool_call_rejected",
    "ultra_plan_raw_output_shape",
    "unavailable",
    "unchanged",
    "verify_canonicalized",
    "verify_command_normalized_at_runtime",
    "verify_command_observed",
    "verify_command_substituted",
    "verify_command_timeout",
    "verify_command_timeout_substitution",
    "verify_default_bound",
    "verify_demoted_advisory",
    "verify_install_substituted",
    "verify_repair_progress",
    "verify_repair_turn",
    "workflow_adjudicated",
    "workflow_edge_fired",
    "workflow_node_run_created",
    "workflow_node_started",
    "workflow_reproducer_bound",
    "workflow_reproducer_prevalidated",
    "workflow_started",
    "workspace_cd_stripped",
    "write_required_off_target_write_allowed",
];

/// Whether `key` is a schema key whose value is a fixed identifier.
pub fn is_fixed_schema_key(key: &str) -> bool {
    FIXED_SCHEMA_KEYS.contains(&key)
}

/// Whether `key` names a container whose direct children are a fixed schema.
pub fn is_fixed_container(key: &str) -> bool {
    FIXED_SCHEMA_CONTAINERS.contains(&key)
}

/// Whether `value` is exactly one of the fixed identifiers.
pub fn is_fixed_identifier(value: &str) -> bool {
    FIXED_IDENTIFIERS.contains(&value)
}

/// Whether a credential/plain value collides with the fixed identifiers.
///
/// True when the value equals a fixed identifier, is a substring of one (a
/// fragment of a fixed identifier would corrupt the schema when redacted), or
/// starts with the reserved `commandagent.` schema prefix. The reverse — a fixed
/// value appearing only inside a longer value — is not a collision.
pub fn collides_with_fixed_identifier(value: &str) -> bool {
    if value.is_empty() {
        return false;
    }
    if value.starts_with("commandagent.") {
        return true;
    }
    FIXED_IDENTIFIERS
        .iter()
        .any(|fixed| *fixed == value || fixed.contains(value))
}
