"""Closed task-family vocabulary shared by formal band classifiers and D-3c.

The tuple is intentionally a literal: the Rust cross-language guard reads it
without executing Python, following the E-5a producer-vocabulary discipline.
"""

TASK_FAMILY_VOCABULARY = ("Quiz", "Breakout", "Space", "aggregation", "timeseries", "stats", "filter", "list", "table", "compile_error_fix", "contract_hook_fix", "pipe", "schema", "unknown")

QUIZ = TASK_FAMILY_VOCABULARY[0]
BREAKOUT = TASK_FAMILY_VOCABULARY[1]
SPACE = TASK_FAMILY_VOCABULARY[2]
AGGREGATION = TASK_FAMILY_VOCABULARY[3]
TIMESERIES = TASK_FAMILY_VOCABULARY[4]
STATS = TASK_FAMILY_VOCABULARY[5]
FILTER = TASK_FAMILY_VOCABULARY[6]
LIST = TASK_FAMILY_VOCABULARY[7]
TABLE = TASK_FAMILY_VOCABULARY[8]
COMPILE_ERROR_FIX = TASK_FAMILY_VOCABULARY[9]
CONTRACT_HOOK_FIX = TASK_FAMILY_VOCABULARY[10]
PIPE = TASK_FAMILY_VOCABULARY[11]
SCHEMA = TASK_FAMILY_VOCABULARY[12]
UNKNOWN = TASK_FAMILY_VOCABULARY[13]

NEXTJS_CREATE_FAMILIES = (QUIZ, BREAKOUT, SPACE)
DATA_CREATE_FAMILIES = (AGGREGATION, TIMESERIES, UNKNOWN)
CLI_CREATE_FAMILIES = (STATS, FILTER)
INGEST_CREATE_FAMILIES = (LIST, TABLE)
NEXTJS_FIX_FAMILIES = (COMPILE_ERROR_FIX, CONTRACT_HOOK_FIX, UNKNOWN)
DATA_INVESTIGATE_FAMILIES = (PIPE, SCHEMA)
