pub(crate) mod approval;
pub mod args_recovery;
pub mod bash;
mod bash_write_guard;
pub mod edit;
pub mod glob;
pub mod grep;
pub mod hidden_path;
pub mod path_guard;
pub mod read;
pub mod registry;
pub mod workspace_policy;
pub mod write;
